# Generated by Django 5.1 on 2024-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('video', models.FileField(upload_to='home_video/%Y/%m', verbose_name='video')),
            ],
            options={
                'verbose_name': 'home video',
                'verbose_name_plural': 'home videos',
                'db_table': 'home_video',
            },
        ),
    ]
